name: Generate GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: hinata-koizumi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_followup: yes

      - name: Commit metrics.svg
        run: |
          if git status --porcelain | grep metrics.svg; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add metrics.svg
            git commit -m "chore(ci): update metrics.svg"
            git push
          fi
